FROM node:22-alpine

WORKDIR /app

# first copy just the package and the lock file, for caching purposes
COPY package*.json ./

# install dependencies
RUN npm i

# copy the entire project
COPY . .

EXPOSE 3001
CMD [ "npm", "run", "dev" ]
